import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const distDir = path.join(projectRoot, "frontend", "dist");
const outDir = path.join(projectRoot, "generated");
const outFile = path.join(outDir, "embedded_assets.hpp");

function listFilesRecursive(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFilesRecursive(full));
    else if (entry.isFile()) out.push(full);
  }
  return out;
}

function toPosix(p) {
  return p.split(path.sep).join("/");
}

function detectMime(relPath) {
  const ext = path.extname(relPath).toLowerCase();
  if (ext === ".html") return "text/html";
  if (ext === ".css") return "text/css";
  if (ext === ".js") return "application/javascript";
  if (ext === ".json") return "application/json";
  if (ext === ".svg") return "image/svg+xml";
  if (ext === ".png") return "image/png";
  if (ext === ".jpg" || ext === ".jpeg") return "image/jpeg";
  if (ext === ".ico") return "image/x-icon";
  if (ext === ".txt") return "text/plain";
  return "application/octet-stream";
}

function byteArrayLiteral(buf) {
  const bytes = Array.from(buf.values()).map((b) => `0x${b.toString(16).padStart(2, "0")}`);
  const lines = [];
  for (let i = 0; i < bytes.length; i += 32) lines.push(bytes.slice(i, i + 32).join(", "));
  return lines.join(",\n      ");
}

if (!fs.existsSync(distDir)) {
  console.error(`Missing frontend build output at: ${distDir}`);
  console.error(`Run: npm --prefix ./frontend run build`);
  process.exit(1);
}

fs.mkdirSync(outDir, { recursive: true });

const files = listFilesRecursive(distDir).sort((a, b) => a.localeCompare(b));
const entries = [];

for (const filePath of files) {
  const rel = toPosix(path.relative(distDir, filePath));
  const data = fs.readFileSync(filePath);
  const varName = `kAsset_${rel.replace(/[^a-zA-Z0-9_]/g, "_")}`;
  entries.push({ rel, data, varName, mime: detectMime(rel) });
}

const cpp = `#pragma once

// Generated by scripts/embed-assets.mjs
// Do not edit by hand.

#include <cstddef>
#include <cstdint>
#include <optional>
#include <span>
#include <string_view>

namespace shine_app::embedded_assets {
  struct AssetEntry {
    const char* path;
    const char* mime;
    const std::uint8_t* data;
    std::size_t size;
  };

${entries
  .map(
    (e) => `  static const std::uint8_t ${e.varName}[] = {
      ${byteArrayLiteral(e.data)}
  };`
  )
  .join("\n\n")}

  static const AssetEntry kAssets[] = {
${entries
  .map((e) => `    {"${e.rel}", "${e.mime}", ${e.varName}, sizeof(${e.varName})},`)
  .join("\n")}
  };

  inline std::optional<AssetEntry> Find(std::string_view relPath) {
    for (const auto& a : kAssets) {
      if (relPath == a.path) return a;
    }
    return std::nullopt;
  }
}
`;

fs.writeFileSync(outFile, cpp, "utf8");
console.log(`Wrote ${outFile} with ${entries.length} embedded files.`);

